services:
  orders-api: # Copy image on Aws repository
    image: id.dkr.ecr.us-east-1.amazonaws.com/[tag]/test:multistage
    ports:
     - 8000:8000
  orders-api-2:
    build:          #Building a image with a dockerfile
      context: .    #path where is the dockerfile
      dockerfile:  Dockerfile.multistage
    ports:
      - 8010:8000
