# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
  namespace: orders-api
# ReplicaSet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-api
  # Pod template
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
        - name: orders-api
          image: 025889067332.dkr.ecr.us-east-1.amazonaws.com/gproyects/test:latest
          ports:
            - containerPort: 8000
          # env:
          #   - name: ENV_TYPE
          #     value: minikube
      imagePullSecrets:
        - name: regcred