apiVersion: v1
kind: Pod
metadata:
  name: orders-api
  namespace: orders-api # declara el namespace donde se encuentra el pod
spec:
  containers:
    - name: orders-api
      image: id.dkr.ecr.us-east-1.amazonaws.com/[]/test:multistage
      ports:
        - containerPort: 8000
      env:
        - name: ENV_TYPE
          value: minikube