pipeline {
    agent any

    environment {
            AWS_REGION = 'us-east-1'
            IMAGE = 'test:latest'
            AWS_ACCOUNT_ID = '025889067332'
            REPO_GH = 'https://github.com/GuidoAnd/proyect-devops-tools-lab.git'
            BRANCH_TARGET_NAME = 'master'
            

    }
    stages {
        
        stage('Clean WS') {
            steps {
                deleteDir()
            }
        }
        stage('Checkout') {
            steps {
                git branch: "${BRANCH_TARGET_NAME}",
                    url: "${REPO_GH}"
            }
        }
        stage('Build Image') {
            steps {
                sh """
                docker build . -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/gproyects/${IMAGE}  
                """
             }
        }
        stage('Tests'){
            steps {
                sh """
                docker run --rm ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/gproyects/${IMAGE} pytest test
                """
            }
        }
        stage('Login to ECR'){
            steps {
                sh """
                aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                
                """
            }
        }
        stage('Push Image') {
            steps {
                sh """
                docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/gproyects/${IMAGE}  
                """
             }
        }
        
    }
}

