pipeline {
    agent any

    stages {
        
        stage('Clean WS') {
            steps {
                deleteDir()
            }
        }
        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/GuidoAnd/proyect-devops-tools-lab.git'
            }
        }
        stage('Build Image')
        {
            steps {
                sh """
                docker build . -t 025889067332.dkr.ecr.us-east-1.amazonaws.com/gproyects/test:latest  
                """
             }
        }
        stage('Tests'){
            steps {
                sh """
                docker run --rm 025889067332.dkr.ecr.us-east-1.amazonaws.com/gproyects/test:latest pytest test
                """
            }
        }
        stage('Login to ECR'){
            steps {
                sh """
                aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 025889067332.dkr.ecr.us-east-1.amazonaws.com
                
                """
            }
        }
        stage('Push Image')
        {
            steps {
                sh """
                docker push 025889067332.dkr.ecr.us-east-1.amazonaws.com/gproyects/test:latest   
                """
             }
        }
        
    }
}

