[api] 
ec2 ansible_host=100.52.177.77 ansible_user=ubuntu ansible_ssh_private_key_file=../PEM/||.pem

[jenkins] 
ec2 ansible_host=100.52.177.77 ansible_user=ubuntu ansible_ssh_private_key_file=../PEM/{}.pem
